FROM        registry.access.redhat.com/ubi8/python-36:latest

USER        root

WORKDIR     /sretoolbox

COPY        . ./

RUN         pip install pipenv
RUN         pipenv install --dev

ENTRYPOINT  ["make"]
CMD         ["check"]
