FROM        centos/python-36-centos7

USER        root

WORKDIR     /sretoolbox

COPY        . ./

RUN         pip install pipenv
RUN         pipenv install --dev

ENTRYPOINT  ["make"]
CMD         ["check"]
