[tool.ruff]
line-length = 88
target-version = 'py311'
required-version = "0.4.2"

src = ["sretoolbox"]
fix = true

[tool.ruff.lint]
preview = true

# defaults are ["E4", "E7", "E9", "F"]
extend-select = [
    # flake8 default rules
    "E1", # preview rule
    "E2", # preview rule
    "W",
    # isort
    "I",
    # pylint
    "PL",

]
ignore = [
    "PLR0913", # Too many arguments
    "PLR0917", # Too many positional arguments
    "PLR2004", # Magic value used in comparison
    "PLR6301", # Method XXX could be a function, class method, or static method
    "PLW1641", # Object does not implement `__hash__` method
]
[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["sretoolbox"]
